apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: secureflow
  labels:                                  # CK-07 REMEDIATED
    app.kubernetes.io/name: transaction-service
    app.kubernetes.io/part-of: secureflow
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-service
  template:
    metadata:
      labels:
        svc: transaction-service
        app.kubernetes.io/name: transaction-service
        app.kubernetes.io/part-of: secureflow
    spec:
      securityContext:
        runAsNonRoot: true                 # CK-04 REMEDIATED
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: transaction-service
          image: secureflow/transaction-service:hardened   # CK-06 REMEDIATED
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: secureflow-config
          env:
            - name: DB_HOST
              value: transaction-db
            - name: DB_NAME
              value: transactiondb
            - name: DB_USER
              value: txuser
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secureflow-config
                  key: TX_DB_PASSWORD
          securityContext:
            privileged: false               # CK-04 REMEDIATED
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:                        # CK-05 REMEDIATED
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: secureflow
  labels:
    app.kubernetes.io/name: transaction-service
    app.kubernetes.io/part-of: secureflow
spec:
  selector:
    svc: transaction-service
  ports:
    - port: 5002
      targetPort: 5002