apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
    app.kubernetes.io/name: transaction-service
    app.kubernetes.io/part-of: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
        app.kubernetes.io/name: transaction-service
        app.kubernetes.io/part-of: secureflow
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transaction-service"
        vault.hashicorp.com/agent-inject-secret-config: "secureflow/data/transaction-service"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secureflow/data/transaction-service" -}}
          DB_PASSWORD={{ .Data.data.DB_PASSWORD }}
          JWT_SECRET={{ .Data.data.JWT_SECRET }}
          {{- end -}}
    spec:
      serviceAccountName: transaction-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: transaction-service
          image: python:3.12-slim
          command: ["sleep", "3600"]
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}